apiVersion: v1
kind: ConfigMap
metadata:
  name: react-app-config
data:
  REACT_APP_API_URL: "http://172.18.0.2:3000" # Change with the address of the kube node 
  REACT_APP_ORG_NAME: "MANIFACTURER Client"
