apiVersion: v1
kind: PersistentVolume
metadata:
  name: react-app-build-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/react-app-build"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: react-app-build-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
