apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  labels:
    app: react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: react
        image: pablomelma/client-side-react-app:latest
        ports:
        - containerPort: 4000
        env:
        - name: REACT_APP_API_URL
          value: "http://express-service.default.svc.cluster.local:3000"
---
apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
    nodePort: 30100  # Ensure this port is within the NodePort range (30000-32767)
  selector:
    app: react
